spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:3306/FiveGears?useSSL=false&serverTimezone=UTC
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080
