spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FiveGears?useSSL=false&serverTimezone=UTC
    username: root
    password: '#Gf48556583830'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # cria/atualiza tabelas automaticamente
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
